version: '2'
services:
    monomvn-app:
        image: monomvn
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://monomvn-mysql:3306/monomvn?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    monomvn-mysql:
        extends:
            file: mysql.yml
            service: monomvn-mysql
